# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ebe04ba6847778976abfc92034e968d1ec3a4f1c139f7e7bd3d305f8ae355be3f5fda61c901df7aad64d7a089e066abedc8529d3461296f0d0ed8c3628218c2

test:
  secret_key_base: ae73b5b0d34fb3a8d7867e344a1c430d5e62a08c120e58fcd93a9377ec836e0218cc2ffd15880153b448fe0aee5d8469269d34ca476a0a40c6d92d84858bfc8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
